resource_group_name          = "rg-terraform-prod-001"
resource_group_location      = "East US"
virtual_network_name         = "vnet-prod-eastus-001"
subnet_name                  = "subnet-prod-eastus-001"
public_ip_name               = "pip-winvm-prod-001"
network_security_group_name  = "nsg-rdpallow-001"
network_interface_name       = "nic-winvm-prod-eastus-001"
windows_virtual_machine_name = "my-win-vm"